index.html
It's a mistake, "you need to be a designer" and not "you need too be a designer".
=> "too" becomes "to"

index.html
Looks even classier with "curly" quotes, doncha think?
=> Upgrade to typographer quotes

CONTRIBUTING.md, README.md
This PR add a contributing guideline that express the current state of the `master` branch. Future Pull Requests will update this file with test or build instructions as we add them into the project.
**Why is the file named CONTRIBUTING.md?**
If you create a file with this name in the root of the project, Github links it when someone tries to create a new issue or Pull Request:
@impress/mergers
=> Create initial version of the CONTRIBUTING.md file

.gitignore, .jshintrc, CONTRIBUTING.md, js/impress.js, package.json
The configs were retrieved from the [jQuery master branch](https://github.com/jquery/jquery/tree/70526981916945dc4093e116a3de61b1777d4718) at the moment this PR was started.
For detailed information on jQuery core style guidelines, see: https://contribute.jquery.org/style-guide/js/
To review, please put `?w=1` in the URL bar in the browser so that Github ignore all whitespace-only changes. [Here is the link](https://github.com/impress/impress.js/compare/master...FagnerMartinsBrack:code-style?w=1).
This closes #529 and (when 0.6.0 is finished) it will also close #426, because then we will have a proper `package.json` to be able to publish the project on npm.
@impress/mergers
=> Apply JSHint and JSCS with jQuery configs

README.md
Rework the introduction to sound less elitist, as suggested by @mattlockyer in the issue https://github.com/impress/impress.js/issues/540.
=> Rework introduction

karma.conf-sauce.js, package.json
Start sauce labs integration to work through items on #575.
This will need  a few things from the maintainers.
=> Add sauce labs integration.

circle.yml, package.json
This adds the last bit to the sauce testing.
I'm not sure how to create a separate job for the run so just mimiced what was in place in circle.yml.
=> Add sauce test script to package.json and command to circle.yml.

.github/ISSUE_TEMPLATE.md
=> Fix wrong URLs in the issue checklist

.github/CONTRIBUTING.md, js/impress.js
=> Corrected the version in the header

js/impress.js, test/core_tests.js
This PR is an attempt to resolve the IE perspective issue described in #476.
=> Break-out perspective for better IE11 support.

js/impress.js
**Make sure these boxes are checked before submitting your Pull Request, thank you!**
=> fix tiny typo

DOCUMENTATION.md
**Make sure these boxes are checked before submitting your Pull Request, thank you!**
=> Fix spelling error in DOCUMENTATION.md

index.html
linking google fonts from http to https
=> changing link fonts.googleapi.com  from http to https

build.js, js/impress.js, src/plugins/rel/rel.js
Just a small fix in the series of PR to dev branch. Please ignore.
=> Add rel goto and skip plugins to build.js too

.jshintrc, build.js, js/impress.js, src/plugins/autoplay/autoplay.js, src/plugins/blackout/blackout.js, src/plugins/extras/README.md, src/plugins/extras/extras.js, src/plugins/form/form.js, src/plugins/help/README.md, src/plugins/help/help.js, src/plugins/impressConsole/README.md, src/plugins/impressConsole/impressConsole.js, src/plugins/mouse-timeout/README.md, src/plugins/mouse-timeout/mouse-timeout.js, src/plugins/navigation-ui/README.md, src/plugins/navigation-ui/navigation-ui.js, src/plugins/progress/README.md, src/plugins/progress/progress.js, src/plugins/skip/README.md, src/plugins/skip/skip.js, src/plugins/substep/README.md, src/plugins/substep/substep.js, src/plugins/toolbar/README.md, src/plugins/toolbar/toolbar.js
This adds all the other plugins into src/plugins, each in their own commits.
ping @bartaz
=> Merge all other plugins

js/impress.js, src/plugins/impressConsole/impressConsole.js
I didn't test this at all, just fixed the obvious. I leave it to whoever merges this to test whether it now actually works. This should fix the bug mentioned in #651.
=> Don't put onclick inside style attribute

src/plugins/help/help.js
As described in #220, I have just added another key press to open plugin help.
=> Help plugin pops up with ?

js/impress.js
As described in #248, added this option for navigation.
=> Shift space going back to previous slide

js/impress.js, src/plugins/autoplay/autoplay.js
This is usefull to request pause/resume from other plugins
=> Add pause and resume events to autoplay

js/impress.js, src/plugins/blackout/blackout.js
- This is the default on Power Point
- THis add support for remote controller presentation blackout key
=> Add support for "." to enter/exit blackout screen

examples/markdown/index.html, js/impress.js, src/plugins/README.md, src/plugins/extras/extras.js
Adding a markdown dialect attribute and passing it to `markdown-js` . Resolves #724
Thanks for the awesome framework!
=> Add markdown dialect attribute.

index.html
It's been almost 9 years since when [impress.js was created](https://github.com/impress/impress.js/commit/0c7f9cc2b14f9a5c68f7847f13a7708934fe16e5). Yes, it's gonna be 10 years in December this year!
Today during some cleaning I even found some of my initial notes for impress.js and presentation!
I've received lots of nice messages over these years on Twitter, but it's also quite a while since I've done anything to the project so it is right about time to remove myself from `index.html` and for sure I'm not the only one to receive the credit for it. 
Thanks everyone who contributed to the project so far!
You have less than a year to think of some 10 year birthday celebrations :D
=> @bartaz removes himself from tutorial text ;)

js/impress.js, src/plugins/extras/extras.js
Dialect is only applied to the last element, so the previous elements will not has dialect.
This PR apply dialect to all markdown elements, so TABLE and other features can be used in all elements.
=> apply markdown dialect to all elements

js/impress.js, src/impress.js
=> Fix typo in impress.js

js/impress.js, karma.conf.js, qunit_test_runner.html, src/impress.js, src/plugins/rel/rel.js, test/plugins/rel/relative_to_screen_size_tests.js, test/plugins/rel/relative_to_screen_size_tests_presentation.html
Add an unittest for #798 , and make an attampt to fix that.
Not a perfect solution, just work.
=> Try fixing relative-to-screen-size calculation
