CHANGELOG.md, LICENSE, README.md
Ping @impress/mergers for review
=> [Doc] Added license, updated Readme and added Changelog file

circle.yml
I noticed the openssl command is failing in circle-ci so seeing if this fixes it.
(there will be rebases until I get it worked out).
=> Fix openssl command.

circle.yml, sauce-encrypted-env-vars
This PR moves creds to the circle-ci accnt config to simplify things and make it work for PRs.
Related to #91. Sauce creds are pretty low worry so the ways things are is a little overkill.
=> Move creds to circle-ci accnt config.

DOCUMENTATION.md, build.js, js/impress.js, src/impress.js, src/lib/README.md, src/lib/gc.js, src/lib/util.js, src/plugins/navigation/navigation.js, src/plugins/resize/resize.js
The next step is to move some of the helper functions into src/lib/*.js files and make them available via impress().lib so that plugins can use them as well. In the code already existing here, navigation plugin uses lib.util.triggerEvent().
The other library is gc, a rather complex "garbage collector" mechanism. It is used to keep track of any changes done to the DOM, mostly as an effect of impress().init(), so that they can be undone with impress().tear(). This was a request in the queue, and I ended up needing it myself too. (The other plugins in my own repo all use this library, so therefore it is merged now.)
@bartaz Based on your comment in the previous PR, I will no longer mark you as a reviewer for PRs, but will continue to ping you so you see these. For this one I will in any case …
=> Common libraries in src/lib

DOCUMENTATION.md
This was probably copy/pasted by mistake, see https://github.com/impress/impress.js/pull/625/commits/8c12757b96f699488de7bc1e257f8365dd3471ae#r143401558
=> Remove second example for ".tear()"

build.js, index.html, js/impress.js, src/impress.js, src/plugins/mobile/README.md, src/plugins/mobile/mobile.js, src/plugins/touch/touch.js
@bartaz : From now on this is basically just more plugins and more stuff. 
This first bucket contains a couple plugins that were hanging around in the PR queue. I have adapted them to the new plugin framework while still putting original author as author. Related to these plugins, the check that prevents from running on mobile phones is removed from core. (I'm aware you've been reluctant to do that, but this is a very common request from community. The mobile plugin attempts to help making presentations consume less memory when targeting mobiles.)
The swipe feature requires working with data structures in core. I've separated out that part, and it adds a new API function: impress().swipe(). The plugin part contains the UI facing part.
In the same PR some unrelated commits to core …
=> Merge mobile stuff

src/plugins/README.md
Fix for issue [#646](https://github.com/impress/impress.js/issues/646) changed the link in the README to point to https://github.com/impress/impress-extras
=> Fixed the link to "extra addons" in the plugins README

CNAME
After @henrikingo has given approval to pursue setting up a custom sub-domain impress.js.org with [dns.js.org](dns.js.org) in issue #655, this creates the [CNAME file](https://help.github.com/articles/setting-up-a-custom-subdomain/) so that the custom domain can be set.
=> add CNAME for impress.js.org (Resolves issue #655)

build.js, js/impress.js, src/plugins/fullscreen/fullscreen.js
- F5 to enter/exit
- Escape to exit
=> Add fullscreen with support to remote presentation controller

js/impress.js, src/impress.js
When swiping to the next page on mobile, the scaling on the current page is massive and interpolates to the correct scale of the next page.
In the code the current page's scale is not corrected for the window's scale, which is corrected in this MR.
For reproducability, visit the demo (https://impress.js.org/) on mobile and swipe to the next page.
Issue that relates to the problem:  https://github.com/impress/impress.js/issues/690
=> Bugfix: Scaling bug on swipe, when window scale is not 1

js/impress.js, src/plugins/substep/README.md, src/plugins/substep/substep.js
Add a `substep.active` class inline with `step.active` to allow styling of the current substep.
Example usage:
```html
<div class="step">
<h2>H2</h2>
<p class="substep single">foo</p>
<p class="substep single">bar</p>
<p class="substep single">baz</p>
</div>
```
```css
.substep {opacity: 0;}
.substep.visible {opacity: 1;}
.substep.single {display: none;}
.substep.single.active {display: block;}
```
=> substep: add substep-active class

src/plugins/media/media.js
The documentation of the media plugin uses `data-media-autostart` instead of `data-media-autoplay`.
=> Fix typo in doc: autostart -> autoplay

js/impress.js, src/lib/util.js, src/plugins/README.md, src/plugins/autoplay/autoplay.js
Adding autoplay URL GET parameter trigger. it will take the duration as value `?impress-autoplay=${duration}`.
- **NOTE**: If the Parameter is passed, it will take precedence over the HTML data parameter.
- **Demo**:
Resolves #720
=> Add autoplay URL parameter trigger.

js/impress.js, src/plugins/impressConsole/impressConsole.js
There is a small typo in js/impress.js, src/plugins/impressConsole/impressConsole.js.
Should read `glitches` rather than `glithes`.
=> docs: Fix simple typo, glithes -> glitches

.circleci/config.yml
It started failing and shouldn't be needed at all.
=> Remove npm-update from CircleCI

js/impress.js, package-lock.json, src/plugins/substep/README.md, src/plugins/substep/substep.js
Thanks for the very helpful project!  For the presentation I'm currently writing, I realized it would be helpful to display substeps in a different order than the one in which they appear in the HTML.  (I could have hacked around that by re-positioning items with CSS, but that would be pretty ugly and not at all semantic).
To fix my issue, I added a feature to the Substep plugin and decided to send it upstream as a PR in case others would also find it useful.
This PR allows users to specify a custom order via the `data-substep-order` attribute.  Substeps without a
`data-substep-order` attribute are revealed last.
This PR also updates the Substep README to document the new feature.
=> Add ability to specify substep order

js/impress.js, src/lib/util.js
``impress.js`` currently gets step id from page hash and pass it to ``byId()`` to jump to specified step.
``byId()`` uses ``document.getElementById( id )``, it works fine with ascii characters.  But for non-ascii ids, it may be url encoded, so ``byId()`` failed to get element by those ids.
This PR uses ``decodeURIComponent( id )`` to decode step id before passing to ``document.getElementById( )``, so it handles unicode step ids too.
=> byId support non ascii characters to support non ascii id for steps

js/impress.js, src/impress.js, src/lib/util.js, src/plugins/rel/rel.js
- move `toNumberAdvanced()` from `rel.js` to `util.js`
- make `data-x`/`data-y`/`data-z` supports relative-to-screen size, like `2w`/`3h`
=> make data-x/y/z supports relative-to-screen size

build.js, examples/3D-positions/index.html, examples/classic-slides/index.html, examples/index.html, js/impress.js, karma.conf.js, package-lock.json, package.json, qunit_test_runner.html, src/lib/rotation.js, src/plugins/rel/README.md, src/plugins/rel/rel.js, test/plugins/rel/padding_tests.js, test/plugins/rel/padding_tests_presentation.html, test/plugins/rel/rel_to_tests.js, test/plugins/rel/rel_to_tests_presentation.html, test/plugins/rel/rotation_tests.js, test/plugins/rel/rotation_tests_presentation.html
The relative position in rel plugin is currently based on the world coordinate. So for the same effect, like fly  in from the right-hand side, we must use difference `data-rel-x`/`y`/`z` value. Why not let the plugin do the hard part?
So I introduce a `data-rel-position`, when set to `relative`, all relative attribute is based on the position and rotation of previous slide. So no matter the rotation of previous slide, `data-rel-x="1000"` always looks like fly in from the right-hand side. We can change the position and rotation of one slide, and the position of all following slides will be changed too.
When `data-rel-position` is set to `relative`, relative rotation has a clear meaning. It describes the relative rotations between slides.   We don't need to set rotations for all slide, …
=> Add relative move and rotate to rel plugin

js/impress.js, src/plugins/rel/rel.js, test/plugins/rel/relative_to_screen_size_tests.js, test/plugins/rel/relative_to_screen_size_tests_presentation.html
e.g.  for `data-x="1w'`, it will be treated as `data-x` is not specified.
=> Fix issue that data-x/y/z can't use relative-to-screen-size unit.

examples/markdown/index.html, js/impress.js, src/plugins/extras/extras.js
1. Support `marked`, you can using it instead. #811
2. Auto detect slide title (using first non-blank line). #816
3. Auto trim the indentation, so it can be indent like regular HTML.
#812
=> Improve markdown support.

examples/3D-positions/index.html
Change `<html>` to `</html>`.
Thanks kuninori.morimoto.gx@renesas.com to point out this.
=> Fix incorrect tag in 3D-positions example

js/impress.js, src/plugins/extras/extras.js, src/plugins/navigation-ui/navigation-ui.js
Markdown slides can be split into multiple slides by `-----`, but currently there's not way to set slide for slides other than the first one.  What this PR does is:
- If a  markdown step has title, use it for the first slide
- Otherwise use the first non-blank line as title for each splited slides
It should make slide navigation easier by a meaningful title.
=> Auto guess slide title from first non-blank line

css/impress-common.css, js/impress.js, src/plugins/impressConsole/impressConsole.js
The impress console is a really useful tool for presenters. As of now, it is however not possible to change the slide's style only for the *slideView* (current slide) or only for the *preView* (next slide). We can't use CSS here as it is not aware of the fact if the page is loaded in an iframe.
The `impressConsole.js` already dynamically adds the class `impress-console` to the body of both iframes. This PR additionally adds the `slideView` and `preView` class, respectively. As a result, we can for instance hide the progress, progressbar and toolbar only in the *preView* using the following CSS snippet:
```css
.impress-console.preView .impress-progress,
.impress-console.preView .impress-progressbar,
.impress-console.preView #impress-toolbar {
display: none;
}
```
A real-world example that …
=> Add .slideView or .preView class if loaded in console

js/impress.js, src/plugins/substep/substep.js
In #779, the ability to add the order of substeps using the `data-substep-order` has been added. The current implementation relies on the assumption that all the given numbers are unique: a sequence `1, 2, 10, 100` is correctly handled, but another `1, 1, 2, 2`  is not. I find the latter very useful to show multiple elements of different DOM nodes in a single substep.
Take for instance a slightly modified version of @codesections' original example from https://github.com/impress/impress.js/pull/779#issuecomment-774574325.
```html
<ul>
<li class="substep"  data-substep-order="0">
TypeScript <span class="substep" data-substep-order="3">(Microsoft)</span>
</li>
<li class="substep"  data-substep-order="1">
Golang <span class="substep" data-substep-order="3">(Google)</span>
</li>
<li …
```
=> Allow multiple data-substep-order with the same value

js/impress.js, src/plugins/substep/substep.js
This PR fixes the default order of substeps, for which no explicit order was given (see issue #855). It ensures that the loop for marking substeps "active" + "visible" is left when at least one substep (with explicit or default order) was marked and this substep uses default order.
Note: The removed space in the header of js/impress.js does not relate to the current issue, but comes from regenerating this file. Apparently the file has not been regenerated when its source file was modified in some previous commit.
=> Fix default substep order when no explicit order given (#855)

examples/classic-slides/index.html
The current HTML in `examples/classic-slides/index.html` is invalid syntax. This PR fixes the two problems.
In 81b49d0ec250e4e4b7b49b381b26cdcf066447e2, I removed the link to the tutorial at all, since inline links are disabled by default since Mermaid.js v8.2.0: see 'click functionality is disabled' in their [release notes](https://github.com/mermaid-js/mermaid/releases/tag/8.2.0).
=> Fix HTML syntax in classic slides example

.github/workflows/pipeline.yaml
This merge request implements the CI/CD pipeline using GitHub Actions.
A step to setup the library and run the tests is pending — will finish it on a different merge request. Once that's completed, the GitHub Actions pipeline will be exactly the same as the Circle CI one.
=> Enable GitHub Actions and Setup Continuous Integration Pipeline
